resource_group_name = "Grouper-Dev"
vnet_name           = "grouper-dev-tf-vnet"
aks_cluster_name    = "aks-grouper-dev-cluster"
name_prefix         = "grouper-dev"
subscription_id     = "f4f3ec7d-9d6f-4752-bdcc-440ed90734fe"
acr_name            = "grouperdevacrpoc"
grouper_image_tag   = "latest"
